
        
server:
    port: 10099
   

    
spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/mirai
feign:
    hystrix:
        enabled: true
    client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 50000
                        
hystrix:
    threadpool:
        default: 
            coreSize: 3 # scale = 0.1
            maximumSize: 5
            allowMaximumSizeToDivergeFromCoreSize: true
            queueSizeRejectionThreshold: 55
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000
            
logging:
    #config: 'classpath:log4j2.yml'
    level:
        #com.mirai.hundun: "INFO"
        #com.mirai.hundun.cp.penguin.feign: "DEBUG"
        #com.mirai.hundun.cp.weibo.feign: "DEBUG"
        #com.mirai.hundun.cp.quiz.feign: "DEBUG"
        org.springframework.web.client.HttpMessageConverterExtractor: "INFO"
        org.springframework.web: "INFO"
        org.springframework.data: "INFO"
        org.springframework.web.client: "DEBUG"

        
